# Generated by Django 4.1.1 on 2022-10-08 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(max_length=50, verbose_name='Usuario'),
        ),
    ]
