# Generated by Django 4.1.1 on 2022-10-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_usuario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.CharField(default='SOME STRING', max_length=50, verbose_name='Email'),
        ),
    ]
